version: '3'

services:
  db:
    image: mariadb:10.3.9
    
    
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cam1810
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: cam1810
  wordpress:
    depends_on:
      - db
    image: wordpress
    
    # La segunda linea de volumes, guarda los archivos que se suban al WordPres, en esa carpeta local.
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress_php:/var/www/html/wp-content
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: cam1810
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data:
    driver: "local"
    driver_opts:
      type: none
      device: $PWD/mysql_wordpress_db
      o: bind
  wordpress_data:
    driver: local